### ISSUE TITLE
IPP URLs in old format

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/w3c-api#103]
The IPP URLs were updated May 3rd, but the W3C API is still returning them in the old URL format. 

For example, `pp-status` below: 

```JSON
{
    "id": 125720,
    "name": "3D FOSS Web Development Community Group",
    "is_closed": false,
    "description": "Our mission is to build and share 3D software that can connect and communicate in free and open ways on AR, VR, and 2D displays.",
    "shortname": "foss-3d",
    "discr": "w3cgroup",
    "type": "community group",
    "_links": {
        "self": {
            "href": "https:\/\/api.w3.org\/groups\/125720"
        },
        "homepage": {
            "href": "https:\/\/www.w3.org\/community\/foss-3d\/"
        },
        "users": {
            "href": "https:\/\/api.w3.org\/groups\/125720\/users"
        },
        "services": {
            "href": "https:\/\/api.w3.org\/groups\/125720\/services"
        },
        "chairs": {
            "href": "https:\/\/api.w3.org\/groups\/125720\/chairs"
        },
        "join": {
            "href": "https:\/\/www.w3.org\/community\/foss-3d\/join"
        },
        "pp-status": {
            "href": "https:\/\/www.w3.org\/2004\/01\/pp-impl\/125720\/status"
        },
        "participations": {
            "href": "https:\/\/api.w3.org\/groups\/125720\/participations"
        }
    }
}
```

**Comment by vivienlacourba** [comment]
Hi @marcoscaceres,

You are right we forgot to update the value of the `pp-status` property.

There was actually another bug as this info is only relevant for groups operating under the W3C Patent Policy which means this property should not exists for Community and Business Groups.

I'm working on a fix to address both issues.

cc: @deniak

**Comment by vivienlacourba** [comment]
@marcoscaceres, issues fixed.

Example of the Accessibility Guidelines Working Group https://api.w3.org/groups/35422:
 ```json
        "pp-status": {
            "href": "https:\/\/www.w3.org\/groups\/wg\/ag\/ipr"
        },
```
Whereas for a Community group (e.g. the 3D FOSS Web Development Community Group https://api.w3.org/groups/125720) the `pp-status` property is not displayed anymore (as not relevant for this type of group).

**Comment by marcoscaceres** [comment]
Amazing! Thank you!
