### ISSUE TITLE
Wrong specification-series names generated for WebCodecs codec registration specs

### ISSUE THREAD

**Issue by tidoust** [w3c/w3c-api#117]
Some WebCodecs codec registration specs have codec names with numbers:

- [`webcodecs-av1-codec-registration`](https://www.w3.org/TR/webcodecs-av1-codec-registration/),
- [`webcodecs-mp3-codec-registration`](https://www.w3.org/TR/webcodecs-mp3-codec-registration/)
- [`webcodecs-vp8-codec-registration`](https://www.w3.org/TR/webcodecs-vp8-codec-registration/)
- [`webcodecs-vp9-codec-registration`](https://www.w3.org/TR/webcodecs-vp9-codec-registration/)

The W3C API incorrectly drops the numbers when it computes the specification series, leading to:

- `webcodecs-av-codec-registration`
- `webcodecs-mp-codec-registration`
- `webcodecs-vp-codec-registration`
- and `webcodecs-vp-codec-registration` again

That's incorrect. The numbers should be kept. The `vp8` and `vp9` specs should create two different series in particular.

**Comment by deniak** [comment]
Indeed, the shortname of the series was incorrectly computed. I've fixed all the records and will track where the bug comes from so it doesn't happen again
