### ISSUE TITLE
Add API to get user by GitHub ID

### ISSUE THREAD

**Issue by darobin** [w3c/w3c-api#12]
We're starting to build a system to track contributions made to GitHub automatically, and notably to be able to flag pull requests as "safe" (because they come from someone we know to be in the group) or "merge with caution" if we're not sure.

In order for that to work, we need to be able to handle GitHub webhooks that give us a GH user ID, and use that to get a W3C user, their affiliation, etc.

I'm not sure what the best way to expose it is; maybe just a redirection from `/github/{id}` to the user?

I'd be happy to discuss priorities for this issue as we are likely to need it sooner rather than later.

**Comment by dontcallmedom** [comment]
as we are making progress in capturing the linked identity between github and w3c accounts, this feature request is becoming important again.

For the repo manager, it would be ideal if we didn't have to manage affiliations there, but instead be able to fetch it automatically from the W3C database, which right now we can only do after having manually established to whom a github account belongs.

(paging @jean-gui since he has been working on the github integration)

**Comment by jean-gui** [comment]
@dontcallmedom How do you see this implemented. Should the URL (/users/github/jean-gui for example) redirect to the corresponding user, or should it display user profile directly?

**Comment by dontcallmedom** [comment]
I have no strong preference, but I suspect having an intermediary resource might become useful, e.g. to show additional metadata about the connection between the w3c & github account (when the connection was made, if it was oauth validated, etc).

I think maybe starting with /users/github/jean-gui giving a simple HAL link to the w3c API endpoint for the user would leave us enough room for improvement.

**Comment by jean-gui** [comment]
I'm not sure it's very useful to provide that intermediate view. All the information about the connection between the w3c and github accounts is already in the user: https://api.w3.org/users/ll90noiui680c8k848sgkcow4ow44ss

**Comment by dontcallmedom** [comment]
ok, then I guess a redirect is probably best (although I would feel better about if if #59 got fixed)

**Comment by sandhawke** [comment]
What's the content at the end of that user link, @jean-gui ?

(I only see Missing API Key, and I don't want to get my heart broken again by digging deeper myself.)

**Comment by jean-gui** [comment]
It's just my user with verified information about my Github account.

**Comment by jean-gui** [comment]
@dontcallmedom Done! See http://api.w3.org/users/connected/github/1479073. Unfortunately you have to use Github IDs rather than logins because this is the only information that we know to be exposed and unique for any OAuth connection (we may want to add more services later).
