### ISSUE TITLE
Search users of an organization who are not participating in any working group

### ISSUE THREAD

**Issue by darthcav** [w3c/w3c-api#127]
Hi, it would be nice, especially for the advisory committee members, to be able to find out which users of his/her own organization are not affiliated to any working group and have a W3C account. Until now, we can only obtain the IDs of those participating in a working group.

**Comment by deniak** [comment]
Hi,

Thank you for your suggestion. After discussing this with some colleagues, this is not something we can expose in the API as the data there is completely public.
However, we added that information at the end of the 'Group participants' tab of your organization page `https://www.w3.org/organizations/<org-id>`.
Please let us know if that solves this issue.

**Comment by deniak** [comment]
Closing this but if it doesn't solve the issue, feel free to re-open

**Comment by darthcav** [comment]
Hi @deniak , that does not solve the issue because I would need a machine-readable list. I know that the list is public, but we coordinate the strategy of my organization within W3C in our internal fora and to keep an up-to-date list, it is very important to have such a list of users. In that way, we could also detect affiliations assigned to us from people who left already our organization.

**Comment by deniak** [comment]
Unfortunately, our current privacy policy doesn't allow us to expose that kind of information on our API. As of today, only the list of participants in public groups can be shared publicly.
