### ISSUE TITLE
Forced paging breaks service

### ISSUE THREAD

**Issue by darobin** [w3c/w3c-api#17]
It used to be that the following worked:

    https://api-test.w3.org/groups?items=500&embed=true

Now it maxes out at 100. This is breaking the [group listing in the repository manager](https://labs.w3.org/hatchery/ash-nazg/admin/groups). I'm not sure what the purpose of this limitation is. The UI needs to show all groups so all that is going to happen is that instead of one request there will be several. The same applies to users in a group: I need to load them all in order to find group intersections. This will just increase the load and the code complexity.

**Comment by vivienlacourba** [comment]
@darobin we have reverted the pagination limit to 100 items so I'm closing this issue. I'll open a new one regarding your comment on low performances.
