### ISSUE TITLE
In API key generation, domains shouldn't restricted to be of the form domain.tld

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/w3c-api#24]
In particular, running an in-browser app from localhost when developing it is rather common :)

**Comment by jean-gui** [comment]
What about creating a key without domain restriction for development? Wouldn't that solve your problem?

**Comment by dontcallmedom** [comment]
I need the domain for CORS to work (right?)

**Comment by jean-gui** [comment]
Done. You can now add localhost. Other domains still require the form domain.tld.
