### ISSUE TITLE
Low performances even on cached pages

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-api#27]
@darobin indicated in [issue #17](https://github.com/w3c/w3c-api/issues/17#issuecomment-128751235) that he was experiencing low performances even when fetching the same resources multiple times which are supposed cached.

I am creating this new seprate issue so that @jean-gui can take a closer look at it.

**Comment by jean-gui** [comment]
@darobin I've made some changes to the caching proxy that should make it more efficient.

**Comment by vivienlacourba** [comment]
FYI upon further testing this issue is really due the time needed to process a request when big roundtrips are involved (eg. over a transatlantic network connection). Note that we have recently increased the pagination limits which enables to reduce the number of requests needed to fetch a full set of results (see issue #48).

**Comment by 4414** [comment]
Please help me with SEO.
http://apartmani-manjarema-fadic.hr/
