### ISSUE TITLE
Inconsistent name for team contacts endpoint and links

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-api#28]
As discussed with @deniak and @tagawa the name of the team contacts endpoint `/groups/*id*/teamcontacts` and the link name used to point to that resource (`_links.team_contacts`) are not consistent (the first one does not contain an `_`).

The endpoint: https://api-test.w3.org/groups/40318/teamcontacts

A link to it as seen in: https://api-test.w3.org/groups/40318

``` JSON
"_links": {
    "id": 40318,
    "name": "HTML Working Group",
    ...
    "team_contacts": 
    {
        "href": "https://api-test.w3.org/groups/40318/teamcontacts"
    },
```

We could `s/teamcontacts/team_contacts/g` as all multi-words data attributes are using underscores (eg. `start_date` ) but so far we don't have any endpoint containing an underscore.

For the record:

``` irc
<denis> vivien, re: s/team_contacts/teamcontacts/, I think we should be consistent. We already have other fields like the feedback dates with that naming convention (e.g. "last_call_feedback_due)
<vivien> denis, but currently we are not consistent as the endpoint (/groups/ID/teamcontacts) and the link name (_links.team_contacts) are different
...
<vivien> we could do the opposite with s/teamcontacts/team_contacts/ (just that till now we did not had any endpoint with an _)
<denis> we should create an issue vivien
* vivien creates it
<denis> GH is using a '_' in its API results
<denis> but I didn't find any endpoints composed with multiple words
<denis> http://stackoverflow.com/questions/778203/are-there-any-naming-convention-guidelines-for-rest-apis
```

**Comment by jean-gui** [comment]
I don't think that's a real issue. I believe that the problem Apiary is facing is rather related to #32.
I'm not against making the API more consistent, but:
- if we change the property name, it becomes inconsistent with other property names
- if we change the URL, it becomes inconsistent with other URLs

Thus, I'd rather leave it as is.
