### ISSUE TITLE
Inconsistent use of “name” and “title”

### ISSUE THREAD

**Issue by tripu** [w3c/w3c-api#30]
In the API, field names `name` and `title` seem to be used indistinctively.

An example: in the data returned by [`https://api-test.w3.org/domains/41381?embed=true`](https://api-test.w3.org/domains/41381?embed=true), the _name_ of the domain is inside `name`; but the _name_ of the domain lead is inside `_links.lead.title` (not `_links.lead.name`).

Another example: in [`https://api-test.w3.org/users/ggdj8tciu9kwwc4o4ww888ggkwok0c8?embed=true`](https://api-test.w3.org/users/ggdj8tciu9kwwc4o4ww888ggkwok0c8?embed=true), the _name_ of the user is inside `name`; but in [`https://api-test.w3.org/users/ggdj8tciu9kwwc4o4ww888ggkwok0c8/specifications?embed=true`](https://api-test.w3.org/users/ggdj8tciu9kwwc4o4ww888ggkwok0c8/specifications?embed=true), the _name_ of the first spec is inside `_embedded.specifications[0].title` (not `_embedded.specifications[0].name`).

A consistent choice would help [Apiary](https://github.com/w3c/apiary) and other HATEOAS clients. Right now, Apiary has to check both fields when it expects a field to contain &ldquo;the name of something&rdquo;.

**I suggest we always use `name`**; I think it's the most generic term, and it's OK for people, groups, institutions, documents, etc.

**Comment by vivienlacourba** [comment]
Hi @tripu, for links the `name` and `title` properties have different meanings and are used correctly in the above examples. Note that there is a difference between "name" being used as a resource property and "name" being used in the context of a HAL link object.

See the "5.5.  name" and "5.7.  title" properties of [Link objects in HAL](https://tools.ietf.org/html/draft-kelly-json-hal-07#section-5).

**Comment by vivienlacourba** [comment]
Maybe we could add a [type property for link objects](https://tools.ietf.org/html/draft-kelly-json-hal-07#section-5.3) with the value `application/hal+json` when we are linking to an API resource, I ma not sure if this is feasible in our current code and will make the API results a bit more verbose.

**Comment by tripu** [comment]
Thanks, @vivienlacourba.
I think I get it.

> _I guess for every {title, href}, I should request that href, and from THAT result, use the field "name"..._

Assigning this pseudo-issue to myself to double-check that that is all I need in Apiary; will follow up.
