### ISSUE TITLE
Provide webhook on TR publication

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/w3c-api#31]
Since TR publications are one of the key aspects on how W3C operates, it would be great if one could register a Webhook that gets invoked each time a TR gets published.

This would for instance enable automatic notifications to mailing lists.

**Comment by tripu** [comment]
This is not exactly what @dontcallmedom suggests, but just as a reminder:
Right now, it is possible to poll the method `echidna/api/status` with the ID of a _publication job_. For example, it would be reasonable to poll it eg every 10&Prime;, maybe for 2&prime; maximum, after a document is submitted to the system. The [JSON response](https://labs.w3.org/echidna/api/status?id=888ecb8d-2379-4b2d-82af-54e2e77a8f1a) can be parsed and a message sent to a mailing list, or whatever.

Anyway, three ideas to achieve what @dontcallmedom wants:
- Have methods **in the API** to register, modify and remove webhooks, associated to specific events (in this case, the event &ldquo;doc published&rdquo;). **Complex**.
- Add a field `webhook` **to the DB of Echidna tokens**. If the field exists and contains a URL, Echidna will POST to that URL after the job finishes. There could be simple interpolation in the URL to pass some parameters along (like the URL of the newly published spec, or a flag to indicate success/failure). **A bit less complex**.
- **In Echidna**, add an argument `webhook` to the method `api/request`. If the argument exists and contains a URL, Echidna will POST to that URL after the job finishes. **Simpler**.

**Comment by dontcallmedom** [comment]
My request was not specifically for echidna-published documents, but for all TR documents that get updated FWIW.

**Comment by deniak** [comment]
@dontcallmedom do you expect these webhooks will be used to get notifications for other kind of events (group creation, user joining groups, etc)? If it's going to be only for TR documents, it will definitely be easier to implement.

**Comment by dontcallmedom** [comment]
hmm… I would think we would want to start with a webhook that only notifies of TR document publications, but I can also imagine us wanting to expand that set of events overtime. In particular, I think the events that get sent should have a type to distinguish between various sources of events (even if initially there is only "TRpublication" as event type)

**Comment by deniak** [comment]
ok, I discussed this with @jean-gui today and we have some ideas on how to implement that system but we need to bring this to the systeam to see what can be done here and when (cc @tguild)

**Comment by tguild** [comment]
agree this would be useful. @dontcallmedom do you have an example service with such a hook in mind to look at?  @deniak as always it is a matter of demand and priorities :) so let me know how much effort you and @jean-gui believe it would take

**Comment by dontcallmedom** [comment]
well, [github webhooks](https://developer.github.com/v3/orgs/hooks/) look like an obvious comparison point :)

**Comment by deniak** [comment]
Github provides an history of each request/response to the webhooks. I think it's not too hard to implement but we need to agree on who can create these webhooks and from where: member visibile page, user profile?

For TR documents, it's ok to share the results with everyone but if we are going to share information about groups and users, we will have to deal with privacy.

**Comment by dontcallmedom** [comment]
re who can create webhooks, I think anyone with a W3C account; we might have to vary what webhooks are available to whom (taking into account your note on the privacy impact of some of the events).

Where — probably the same as API key, i.e. user profile for now; we might have to migrate these to a different entry points at some point, but I don't think it's critical, and I hope it shouldn't matter too much in terms of development.

**Comment by tguild** [comment]
@deniak until (if) we come up with ACLs on more private/sensitive information we need to treat everything as public.  As such only you should only be able to put hooks on open data like TR for now. Those with API keys (that presently requires a W3C account) should by extension be able to create hooks.

**Comment by vivienlacourba** [comment]
For our inspiration here is a pointer to [GitLab's webhooks documentation](http://doc.gitlab.com/ce/web_hooks/web_hooks.html).

**Comment by sandhawke** [comment]
It'd definitely be nice to have this for people joining or leaving a group, too.     And probably any other data change event.  So don't make it TR specific, please.

**Comment by jean-gui** [comment]
Webhooks support is coming up soon, starting with TR publications. Group joins/leaves will quickly follow but require a little more work.

**Comment by jean-gui** [comment]
Head to https://www.w3.org/users/myprofile/webhooks to setup new webhooks.

I'm closing this issue and will create another one for people joining/leaving groups.

**Comment by dontcallmedom** [comment]
The URI exposed by the webhooks are `http:`URIs; it would seem more aligned with our new setup to use `https:` URIs.
