### ISSUE TITLE
items parameter not taken into account on /specifications/{shortname}/versions/{date}/previous

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-api#33]
The `items` parameter used to control how many items are displayed on paginated results is not taken into account on `/specifications/{shortname}/versions/{date}/previous` (and I believe there is a similar issue for `.../next`).

See for example the version below which has 4 previous versions. I requested only 2 items per page but got 4 items.
https://api-test.w3.org/specifications/WCAG20-TECHS/versions/20060427/previous?items=2

**Comment by jean-gui** [comment]
Fixed. Will be deployed later.
