### ISSUE TITLE
Collision on previous and next relation names

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-api#34]
In `/specifications/{shortname}/versions/{date}/previous` the `previous` relation is used to link to previous version(s) of a given specification version, unfortunately that name is already used by the pagination module to indicate the previous result page.
This leads to strange results as both links are being merged together.

See for example:
https://api-test.w3.org/specifications/WCAG20-TECHS/versions/20060427/previous?page=2
(with `page=2` to force the previous pagination link)

The exact same issue exists with `next`.

A solution would be to rename our `previous` rel in `previous-version` or, as proposed by the [IANA Link Relations Registry](http://www.iana.org/assignments/link-relations/link-relations.xhtml) and [RFC5829 - Version Navigation Link Relations](http://tools.ietf.org/html/rfc5829), call it `predecessor-version`.

> 3.5.  'predecessor-version'
> 
>  When included on a versioned resource, this link points to a resource
>  containing the predecessor version in the version history.
> 
>  Some systems may allow more than one of these link relations in the
>  case of multiple branches merging.

**Comment by jean-gui** [comment]
I don't think that predecessor-version corresponds to what we model here. In our case we have several previous versions, but predecessor-version only makes sense for branches merging

**Comment by vivienlacourba** [comment]
If we go for the above mentioned `predecessor-version` and `successor-version` we should also use the `version-history` and `latest-version` relation names which are also part of [RFC5829 - Version Navigation Link Relations](http://tools.ietf.org/html/rfc5829).

**Comment by jean-gui** [comment]
Changes to be deployed soon on link rels:
- parent -> up
- previous -> predecessor-version (for spec versions)
- next -> successor-version (for spec versions)
- versions -> version-history (for spec versions)
- first -> first-version (for specs)
- latest -> latest-version (for specs)

And URLs :
- /specifications/xxx/versions/yyy/previous -> /specifications/xxx/versions/yyy/predecessors
- /specifications/xxxversions/yyy/next -> /specifications/xxx/versions/yyy/successors
