### ISSUE TITLE
Give participation affiliation in groups user list

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/w3c-api#37]
In some groups (typically, WGs, IGs, CGs), people participate as representative of another group (typically, a Member org); as far as I can tell, that (very useful) information is not currently available in the API.

(one can retrieve the list of the users's affiliation, but not the one that specifically "sponsors" the participation in the said group)

**Comment by vivienlacourba** [comment]
Hi @dontcallmedom we have discussed this with @jean-gui and have created a proposal which is detailed in issue #43.

**Comment by jean-gui** [comment]
@dontcallmedom Can you confirm that https://github.com/w3c/w3c-api/issues/43 would solve this issue?

**Comment by dontcallmedom** [comment]
I believe it would (I hope you were not waiting for my reply or validation)

**Comment by jean-gui** [comment]
No, #43 is implemented and ready to deploy. I was simply wondering if something more would be needed for your use case.
