### ISSUE TITLE
Get rid of discr property and merge it with type

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-api#39]
type property is needed on:
- `groups` (various types of groups wg / ig / bg / cg)
- `affiliations` (to differentiate between affiliation and organization)
- Not needed elsewhere as it is obvious which type of object we are getting based on the endpoint

**Comment by jean-gui** [comment]
discr is present because it would be necessary for deserialization (in case of a POST or PUT). It is possible to rename it, but then you also have to explicitly add all the value<->class pairs, which will be a pain to pain.

I think it's better to let it be.

**Comment by vivienlacourba** [comment]
I agree.
