### ISSUE TITLE
New endpoint for W3C Group participations

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-api#42]
New participation endpoint:
- `/participations/{participation-id}` an entity's (individual or organization) participation in a W3C Group
  - a `type` property with value `organization/individual`
  - `created` and `ended` properties (find good names)
  - a `group` link
  - a `user` link (only if `type=individual`)
  - an `organization` link (only if `type=organization`)
  - a `participants` link (see below only if `type=organization`)
- `/participations/{participation-id}/participants` list of users participating in this group sponsored by this affiliation

**Comment by jean-gui** [comment]
Will be deployed soon
