### ISSUE TITLE
Add participations information for affiliation, groups and users

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-api#43]
As group participation is now public we can add a few more routes related to organizations and affiliations' participations.

This would enable to create based on the API pages like the [IPP status page](https://www.w3.org/2004/01/pp-impl/47318/status) and should answer @dontcallmedom request #37.

On affiliations add the following links and subpages:
- `/affiliations/{aff-id}/participations` list of participations in public groups (wg/ig/cg/bg) for this affiliation
- `/affiliations/{aff-id}/participants` list of all users participating in public groups sponsored by this affiliation

On groups add:
- `/groups/{group-id}/participations` list of participations in that group

On users add:
- `/users/{user-id}/participations` list of participations for that user

This depends on issues:
- [x] `/affiliations` endpoint (see #40)
- [x] `/participations` (see #42)

**Comment by jean-gui** [comment]
Will be deployed soon
