### ISSUE TITLE
Increase maximum number of items on paginated results

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-api#48]
We got several requests asking to increase the number of items per page (some people even asked us to get rid of pagination, see issue #46 from @sandhawke).

While it does not seem feasible to completely remove pagination (as we already experience it when we reached memory limits), we should be able to increase the current maximum which is at 100 to an higher number. That number would be determined by testing our various endpoints, and also tuning of PHP's max memory setting.

Additionally this would reduce the number of request to retrieve a full list of results, which would be a performance increase for users that are not local to MIT.

**Comment by jean-gui** [comment]
Maximum increased to 1000, and default is now 100.
