### ISSUE TITLE
Harmonize property and rel names

### ISSUE THREAD

**Issue by deniak** [w3c/w3c-api#50]
#47 suggests we use `-` instead of `_` in rel names. We should have the same format for property names as well.

**Comment by vivienlacourba** [comment]
@deniak before proceeding with that change it would be good to measure its impact on applications relying on the API. Could you coordinate with @tripu regarding impact on [apiary](https://github.com/w3c/apiary) and also with @dontcallmedom to inform him of that change ?

**Comment by deniak** [comment]
I created a MR for [node-w3capi](https://github.com/w3c/node-w3capi): https://github.com/w3c/node-w3capi/pull/3.

**Comment by vivienlacourba** [comment]
This modification has been merged and will be deployed on Monday 12 Oct in the morning.

**Comment by tripu** [comment]
w3c/apiary#27 is ready to be merged in sync with this rollout of the new API version.

I shall be online on Monday to solve issues with Apiary&nbsp;&mdash;&nbsp;a few hours after the deployment, the latest.
