### ISSUE TITLE
Spec Version History in API Differs from History in HTML Page 

### ISSUE THREAD

**Issue by hariharshankar** [w3c/w3c-api#52]
The version history of specifications provided by the API is different from the version history available in the HTML version of the spec.
For example:
The page http://www.w3.org/TR/xslt lists 7 versions:

http://www.w3.org/TR/1999/REC-xslt-19991116
http://www.w3.org/TR/1999/PR-xslt-19991008
http://www.w3.org/1999/08/WD-xslt-19990813
http://www.w3.org/1999/07/WD-xslt-19990709
http://www.w3.org/TR/1999/WD-xslt-19990421
http://www.w3.org/TR/1998/WD-xsl-19981216
http://www.w3.org/TR/1998/WD-xsl-19980818

while the API https://api-test.w3.org/specifications/xslt/versions?_format=json only returns 4 versions:

```
...
version-history: [
            {
                href: "https://api-test.w3.org/specifications/xslt/versions/19991116",
                title: "XSL Transformations (XSLT) Version 1.0"
            },
            {
                href: "https://api-test.w3.org/specifications/xslt/versions/19991008",
                title: "XSL Transformations (XSLT) Version 1.0"
            },
            {
                href: "https://api-test.w3.org/specifications/xslt/versions/19990813",
                title: "XSL Transformations (XSLT) Version 1.0"
            },
            {
                href: "https://api-test.w3.org/specifications/xslt/versions/19990709",
                title: "XSL Transformations (XSLT) Version 1.0"
            }
        ] 
...
```

**Comment by deniak** [comment]
@hariharshankar, thanks for the report. It's now fixed.
