### ISSUE TITLE
Add webhook support for people joining/leaving groups

### ISSUE THREAD

**Issue by jean-gui** [w3c/w3c-api#62]
Suggested by @sandhawke : "It'd definitely be nice to have this for people joining or leaving a group, too. And probably any other data change event. So don't make it TR specific, please."

**Comment by plehegar** [comment]
adding @dontcallmedom on this one since we'd love this

**Comment by jean-gui** [comment]
This has finally been added. See https://w3c.github.io/w3c-api/webhooks for more info.
