### ISSUE TITLE
Inconsistent URL Protocol in Version API

### ISSUE THREAD

**Issue by hariharshankar** [w3c/w3c-api#63]
The embedded version history API responds with a mixture of http:// and https:// URLs. 

For example: https://api.w3.org/specifications/xslt/versions?_format=json&embed=1&apikey= 
returns 

```
{
...
_embedded: {
  version-history: [
    {
      status: "Recommendation",
      uri: "http://www.w3.org/TR/1999/REC-xslt-19991116",
      date: "1999-11-16",
      informative: false,
      title: "XSL Transformations (XSLT) Version 1.0", 
      shortlink: "http://www.w3.org/TR/xslt",
      errata: "http://www.w3.org/1999/11/REC-xslt-19991116-errata",
      _links: {
         self: {
            href: "https://api.w3.org/specifications/xslt/versions/19991116"
         },
         editors: {
           href: "https://api.w3.org/specifications/xslt/versions/19991116/editors"
         }, ...
  }
},
...
}
```

Since W3C moved fully to https recently, I presume all these URLs should be https?

**Comment by plehegar** [comment]
:+1: to return https link from our API

**Comment by plehegar** [comment]
Here is the proposal:
https://lists.w3.org/Archives/Public/spec-prod/2016AprJun/0024.html

**Comment by vivienlacourba** [comment]
All uris related to W3C publications are now using HTTPS exclusively since 6 July 2020.

See https://lists.w3.org/Archives/Public/spec-prod/2020JulSep/0001.html
