### ISSUE TITLE
Expose list of groups of which the user is chair or staff contact

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/w3c-api#67]
When building customized views, it is often useful to put forward groups in which a given user has a special role. For instance, in ash-nazg, there is a pending [feature request to filter PRs most relevant for the user](https://github.com/w3c/ash-nazg/issues/9).

To do that, it would be great if the API could expose somewhere in /user/foobar/ the list of groups from which the user is a chair or a staff contact.

**Comment by vivienlacourba** [comment]
+1 this request sounds good to me.

We could implement this by adding new endpoints to a user, eg.
- `https://api.w3.org/users/1234/chair-of-groups` -> would return a list of group for which user 1234 is a chair
- `https://api.w3.org/users/1234/team-contact-of-groups` -> would return a list of group for which user 1234 is a team contact

**Comment by dontcallmedom** [comment]
any news on this?

**Comment by jean-gui** [comment]
Should be merged soon.
