### ISSUE TITLE
Please open the group

### ISSUE THREAD

**Issue by darobin** [w3c/w3c-api#7]
This group started off open, it should not be closed.

I know that the API isn't announced yet (though it's public), but this repo was created for the specific purpose of gathering feedback from early adopters whom we've pointed at the API. They can't do that now. If it's to have a closed group why not just stick to the GitLab instance?

**Comment by darobin** [comment]
\o/

Can we talk about it?

**Comment by deniak** [comment]
@darobin  go ahead!

**Comment by tripu** [comment]
Hum&hellip; I guess it'll be fine for me to [release the bees](https://github.com/w3c/apiary), then&hellip;

**Comment by tguild** [comment]
:) at bees
