### ISSUE TITLE
Expose whether a specification is intended to go to Recommendation

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/w3c-api#70]
I understand that we keep track of which specifications are intended to go to Rec (vs intended to be published as a Note); it would be useful for one of my projects to have access to that information in the W3C API.

**Comment by deniak** [comment]
@dontcallmedom we have that information per dated version, not per specification. Is that helpful to you?

**Comment by dontcallmedom** [comment]
sure

(in an ideal world, the info of the latest version would be available readilly from the short name end point to avoid multiple requests, but in any case, starting with it being on the latest version is enough for my current purpose)

**Comment by deniak** [comment]
The API now exposes a new property `rec-track` on each version
