### ISSUE TITLE
“/versions/{date}/predecessors” and “/versions/{date}/successors”: property names in “_links” and “_embedded” are not coherent

### ISSUE THREAD

**Issue by tripu** [w3c/w3c-api#72]
After the changes in #34 (`predecessor-version` and `successor-version`), the name of the arrays returned are not consistent.

For example:

```json
{
  "_links": {
    "predecessor-version": [
      {
      }
    ]
  },
  "_embedded": {
    "versions": [
      {
      }
    ]
  }
}
```

Shouldn't `versions` above be `predecessor-version`, too?

I think some clients (eg, `node-w3capi`) operate under the assumption that those two IDs are always the same, and it would be nice not having to make and exception in the code just for these two cases.

**Comment by jean-gui** [comment]
@deniak agreed to look into it

**Comment by tripu** [comment]
Any progress with this one&hellip;?

**Comment by deniak** [comment]
Not yet @tripu. I'll try to tackle that issue this week.

**Comment by deniak** [comment]
should be fixed now
