### ISSUE TITLE
How to call this from C#?

### ISSUE THREAD

**Issue by egkareem** [w3c/w3c-api#78]
Hot to use the API from C#.NET Console application for example to validate an HTML file residing on disk?

**Comment by tripu** [comment]
@ekareem: the W3C API serves data about working groups, users, specs, etc (see [the overview](https://w3c.github.io/w3c-api/) and [the documentation](https://api.w3.org/doc)). It is *not* intended to validate documents.

For information about installing a markup validator locally, see projects [w3c/markup-validator](https://github.com/w3c/markup-validator/) and [validator/validator](https://github.com/validator/validator/).

**Comment by egkareem** [comment]
Got it. Thank you.
