### ISSUE TITLE
Give access to past group members

### ISSUE THREAD

**Issue by iherman** [w3c/w3c-api#80]
(This is related to #68, but it is not exactly the same.)

I know that `/groups/{group}/users` can be used to retrieve the members of a group. However, there is no analogous to

    https://www.w3.org/2000/09/dbwg/details?group={group}&former=1

ie, to get the list of _all_ group members, past and present.

I use the API-s to automatically generate the acknowledgement section of a spec, simply listing all members of the group. It would be unfair if, say, when publishing the Rec only the then active members of the group were listed and not the past...

**Comment by iherman** [comment]
It seems that this request went down the drain... Any reaction on it? @tripu @deniak @jean-gui ?

**Comment by 123georgesteve** [comment]
My wife totaled the car and I have no idea how to get set up

**Comment by tripu** [comment]
I think @jean-gui or @vivienlacourba will be the best to evaluate the feasibility of this.

**Comment by iherman** [comment]
I am still waiting to see if somebody cares about this request... :-(

@jean-gui @vivienlacourba @tripu

**Comment by jean-gui** [comment]
Implemented. See https://api.w3.org/doc#get--groups-{group}-users and https://api.w3.org/groups/47318/users?former=true

**Comment by iherman** [comment]
Thank you @jean-gui !

**Comment by willinghamtravis360-max** [comment]
H
