### ISSUE TITLE
403 response "Invalid API key message" received once in a while

### ISSUE THREAD

**Issue by tidoust** [w3c/w3c-api#83]
Some of my tools use the W3C API to retrieve information about specs and groups: [Reffy](https://github.com/tidoust/reffy) notably, and now playing with the API for [roadmaps](http://github.com/w3c/web-roadmaps).

Once in a while, the W3C API server rejects a request with a 403 response and the following message:

```json
{    "message": "Invalid API key",    "documentation_url": "https://github.com/w3c/w3c-api"}
```

Re-issuing the request solves the issue. The type of request does not seem to matter. The number of requests to send before this error occurs varies. Sometimes, it's after 30 requests. Sometimes, after 80 requests. Sometimes, after 200 requests. And sometimes I don't get the error.

My projects typically send something like a few hundred requests to the W3C API server. Initially, I thought the problem might be too many requests in parallel, but my code actually wait for a response before it sends another request, so there must be another explanation. Perhaps some transient communication issue between the server and the database when the server is under stress?

**Comment by tidoust** [comment]
By the way, we don't have good logs for Reffy, but the tool runs every night and sends us an email report. First errors that "look like" this bug reached my inbox on **2 March 2018 at 2:12am UTC**, so if you changed something early March, that might be a good place to look at. We've seen similar error reports roughly once every two days during March.

**Comment by jean-gui** [comment]
This should be fixed.
