### ISSUE TITLE
Incomplete return for a WG?

### ISSUE THREAD

**Issue by iherman** [w3c/w3c-api#84]
I inquire the group 100074. I use:

https://api.w3.org/groups/100074/users?apikey=...

However, the result is incomplete. Looking at 

https://www.w3.org/2000/09/dbwg/details?group=100074

The last four entries (after Jeff Xu) are missing:-( 

@tripu @deniak ?

**Comment by jean-gui** [comment]
There's a second page https://api.w3.org/groups/100074/users?page=2. Check out attributes "pages" and "next".

**Comment by iherman** [comment]
Oops... RFM:-)

and yes, it works. Thanks!
