### ISSUE TITLE
Add Swagger/OpenAPI files to repo

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/w3c-api#85]
Mainly, I'm looking for a way to contribute directly the API (but can't find the code/docs). The [docs](https://api.w3.org/doc) look like they were output from Swagger/OpenAPI docs (with which I'm familiar), so if sending PRs against that is a sensible way to contributed, I'd be happy to do that!

Cheers!
🎩

**Comment by tripu** [comment]
Thank you, @BigBlueHat!

The source code is not public on GH, since it's too dependent on our DB schema etc. But perhaps @jean-gui or @deniak can tell us about the feasibility of adding those files to the repo.

**Comment by jean-gui** [comment]
Unfortunately, this documentation is generated from annotations in the code, we don't have any Swagger source files, and as @tripu said, the code is not public. I think the only way to propose changes to the documentation is by opening new issues.
