### ISSUE TITLE
is a participant an IE?

### ISSUE THREAD

**Issue by plehegar** [w3c/w3c-api#90]
For a given group, one has to do the following to know if it's an invited expert:
 https://github.com/w3c/gargantua/blob/master/w3c.js#L29

It would be nice if we can return a boolean flag, when accessing group/participations or group/users, that gives this indication.

**Comment by jean-gui** [comment]
I have added a property to https://api.w3.org/participations/21634, which can also be grabbed directly from the list of participations using the embed parameter: https://api.w3.org/groups/35422/participations?embed=true

Does that fit your needs?

**Comment by plehegar** [comment]
Works wonderfully https://github.com/w3c/gargantua/commit/5a8fab9ad06cd696f77e190ff2a26ab27abd32a2
