### ISSUE TITLE
Group shortnames

### ISSUE THREAD

**Issue by plehegar** [w3c/w3c-api#91]
Our DB knows about *some* group shortnames, eg
 Shortname: distributed-tracing
 https://www.w3.org/groups/w3cgroups/108594

Can we add this field into the group object returned by our API please?

Can we have a way to edit/add shortnames, such as for
 https://www.w3.org/groups/w3cgroups/35422 ?

Note: for consistency purposes, I suggest it shouldn't be possible to reuse the same name of an active group of the same type.

cc @dontcallmedom

**Comment by vivienlacourba** [comment]
Hi @plehegar @dontcallmedom 

> Our DB knows about _some_ group shortnames, eg
> Shortname: distributed-tracing
> https://www.w3.org/groups/w3cgroups/108594
> 
> Can we add this field into the group object returned by our API please?

The notion of group shortname was introduced for community groups and is also available for other types of groups. Unfortunately for old groups the info is incomplete and often missing.

What is/are your use case(s)?
Do you need it for other type of groups than WGs and IGs (we have it already for all CGs and BGs)?

> Can we have a way to edit/add shortnames, such as for
> https://www.w3.org/groups/w3cgroups/35422 ?
> 
> Note: for consistency purposes, I suggest it shouldn't be possible to reuse the same name of an active group of the same type.

We have such a feature but it is limited to systeam (as renaming an existing shortname requires other systems changes besides the db change).

For groups that don't have shortnames we can set this info if you provide us the list of missing shortnames in the form of:
```
group1_id,group1_shortname
group2_id,group2_shortname
...
```

Please note that shortnames:
* are unique across all types of group (meaning you will not be able to use `auto` for both the WG and the BG) and all statuses (meaning you won't be able to reuse the shortname of a closed group).
* must be between 2 and 24 characters long containing only alphanumeric characters of lower case and hyphen with a letter at the first position. Corresponding pattern: `^[a-z][a-z0-9-]{0,22}[a-z0-9]$`
* need to be well thought out as they are very costly to change afterwards
 
Once we have that info for all existing groups, we can make shortname a required info when new groups are created and also expose it in the api.

**Comment by plehegar** [comment]
Doing it all at once won't work for me. I need to show things to folks to get them interested in fixing the data. Sending an email to chairs and TCs on a limb of an idea isn't going to work.

Until I show them URLs, they won't be motivated in shortnames. So, I need to do it piecemeal, when folks ask for it. If that doesn't work for you, I can do my own JSON to store the shortnames. Once I do the JSON, it's unlikely that I'll come back to you when it's done, since all of our systems will use the JSON instead at that point and we won't need the endpoint in our API anymore. I can grab the shortname by parsing the HTML page of the group today, so I'll get them to notice those and point them to my JSON to override them overtime. So, maybe we can find a middle ground approach.

**Comment by swickr** [comment]
@vivienlacourba,

> Once we have [shortnames] for all existing groups, we can make shortname a required info when new groups are created and also expose it in the api.

Can't the API return the null string for groups where no shortname is defined?  Why is that API enhancement dependent on fully populating the data?

**Comment by vivienlacourba** [comment]
@swickr technically yes it can certainly return null so could any other field.

But the important part is that today we don't store (nor have) that data for any WG/IG/Task force/... only for CG and BG (because in the CG context shortnames are central, they serve as identifier and control the URI space or the mailing list names).

I am very keen on providing all the data we have but when we don't have it I'd like to first understand what should be the data we would like to store, what are our initial use cases before committing on exposing it.
This is what I tried to get clarification on from @plehegar when I asked:

> What is/are your use case(s)?
> Do you need it for other type of groups than WGs and IGs (we have it already for all CGs and BGs)?

Note that I also pinged @dontcallmedom to get an answer but he did not had more info on this.

**Comment by marcoscaceres** [comment]
This would be amazing for ReSpec too... we are currently making up our own names. See:
https://github.com/marcoscaceres/respec.org/pull/91 

That way we don't need to maintain the list in ReSpec.

cc @sidvishnoi

**Comment by marcoscaceres** [comment]
See also https://github.com/w3c/respec/wiki/group ... I think BikeShed does something similar.

**Comment by vivienlacourba** [comment]
Since the introduction of the new groups pages in June 2020, all groups listed on the [W3C Groups](https://www.w3.org/groups/) page now have a shortname which is also exposed in the W3C API .
This include all WGs, IGs, CGs, BGs, TAG, AB along with their corresponding task forces.

Note:
* For new groups shortnames are set during their creation
* The same shortname can be used for groups of different types

Example for the Accessibility Guidelines Working Group https://api.w3.org/groups/35422:
```json
{
    "id": 35422,
    "name": "Accessibility Guidelines Working Group",
    (...)
    "shortname": "ag",
    "type": "working group",
    (...)
}
```

**Comment by marcoscaceres** [comment]
Not sure where to ask, but maybe we can get the short names more easily exposed at W3C Groups? I'd love to point people to https://www.w3.org/groups/ instead of https://respec.org/w3c/groups/

**Comment by deniak** [comment]
@marcoscaceres https://www.w3.org/groups/ only lists the different types of W3C groups.
Would it be ok to have the shortnames displayed below the group names under each page?
* https://www.w3.org/groups/wg/
* https://www.w3.org/groups/ig/
* https://www.w3.org/groups/cg/
* https://www.w3.org/groups/bg/

/cc @jean-gui

**Comment by marcoscaceres** [comment]
> Would it be ok to have the shortnames displayed below the group names under each page?

I think it would be fine. Main thing is being able to quickly search for them, which folks can do via browser's in-page search.

**Comment by deniak** [comment]
@marcoscaceres we ended up displaying the shortname on the group page itself, e.g. https://www.w3.org/groups/wg/css.
It was suggested to keep the data on the list of groups minimal and put that kind of additional data on separate pages.

**Comment by marcoscaceres** [comment]
Ok cool! thanks for the update!
