### ISSUE TITLE
New endpoint to retrieve levels of a "shortname without level"

### ISSUE THREAD

**Issue by tidoust** [w3c/w3c-api#98]
My understanding of the discussion in #96 is that it deals with what the API should return for a request on a "shortname without level", e.g. for queries "hr-time" instead of on "hr-time-2".

Another information that would be useful for me is a mechanism to list the different levels that exist for a given "shortname without level". Right now, I can either query:

- `/specifications/{shortname}` but, even if #96 gets fixed, this will only give me some information about the latest version of the current level of a spec.
- `/specifications-by-shortname/{shortname}` but that can easily give me a list with way more specifications than the ones I'm interested in (for instance, a query on "css" retrieves a bunch of spec, and not only the CSS Snapshots such as "css-2013").

Actually, I do not know whether that association between a "shortname without level" and existing levels exists in our system. It may be that our system only knows about the association of a "shortname without level" with the current "shortname with level"?

If we do have that information, could it be exposed somehow?

**Comment by vivienlacourba** [comment]
Hi @tidoust,

> Actually, I do not know whether that association between a "shortname without level" and existing levels exists in our system. It may be that our system only knows about the association of a "shortname without level" with the current "shortname with level"?

You guessed right we do not have that info in our db yet.

Good news is that @deniak is currently working on adding it by implementing levels in addition to shortnames with and without the level info. You comment is quite timely to help sketch up the changes on the API, @deniak will get back to you in the next 2-3 weeks.

**Comment by deniak** [comment]
`/specification-series/` has been deployed.
