### ISSUE TITLE
Wiki Login problem

### ISSUE THREAD

**Issue by hoijui** [w3c/w3c-api#99]
I know I am horribly wrong here, and I am sorry, but.. I really could not find a way to report this issue on the w3c website.
I created two logins through <https://www.w3.org/accounts/request>, and while I confirmed both of them (email verification), and I can login on <https://www.w3.org/users/myprofile>, I can not login on the Wiki: <https://www.w3.org/2001/sw/wiki/index.php?title=Special:UserLogin>.
Can you please forward this, or tell me where to go with this issue?
thanks and sorry!

**Comment by vivienlacourba** [comment]
Hi @hoijui,

Please resend your issue by email to the W3C Systems support list: sysreq@w3.org

Regards,
Vivien

**Comment by HuanWuCode** [comment]
I ran into the same issue and sent an email to sysreq@w3.org

**Comment by hoijui** [comment]
I did the same now

**Comment by hoijui** [comment]
This is the answer I got:

> The login page for this wiki mentions that it "is restricted to members of one or several W3C groups".
The wording on that page is a bit vague, but in this case it means that it is restricted to W3C Members and participants in the RDF-DEV Community Group (https://www.w3.org/community/rdf-dev/).
